2024-11-09 16:57:15,435 | WARNING | Неверный тип данных для объекта Runner 
Traceback (most recent call last):
  File "P:\Projects\python\pythonProject\module_12\runnerTest_12_4.py", line 23, in test_run
    ben = Runner(68, 4)
          ^^^^^^^^^^^^^
  File "P:\Projects\python\pythonProject\module_12\runner_12_4.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-09 16:57:15,437 | WARNING | Неверная скорость для Runner 
Traceback (most recent call last):
  File "P:\Projects\python\pythonProject\module_12\runnerTest_12_4.py", line 12, in test_walk
    nick = Runner("Nick", -5)
           ^^^^^^^^^^^^^^^^^^
  File "P:\Projects\python\pythonProject\module_12\runner_12_4.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
